# 1.4.4 Smoothing Images

## Kernel Convolution

In [38]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [39]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [40]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [41]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [42]:
img

array([[2, 2, 3, 3, 9, 1, 0, 6, 1, 4, 1, 6],
       [2, 2, 4, 9, 2, 2, 0, 5, 7, 3, 3, 3],
       [8, 0, 2, 5, 4, 2, 4, 6, 5, 1, 0, 2],
       [8, 4, 2, 4, 3, 0, 7, 8, 3, 5, 1, 4],
       [7, 4, 3, 7, 0, 2, 1, 1, 4, 5, 3, 0],
       [3, 6, 8, 9, 3, 9, 8, 5, 5, 4, 8, 8],
       [4, 0, 3, 8, 1, 6, 5, 8, 1, 9, 1, 5],
       [4, 2, 1, 4, 7, 0, 8, 1, 6, 7, 8, 1],
       [1, 2, 9, 0, 0, 4, 9, 6, 7, 6, 3, 8],
       [4, 0, 4, 0, 3, 2, 5, 4, 6, 8, 2, 5],
       [4, 7, 7, 1, 9, 7, 2, 9, 2, 9, 8, 3],
       [5, 3, 5, 1, 1, 9, 8, 1, 8, 5, 8, 5]])

In [43]:
h,w=img.shape

In [44]:
print(h,w)

12 12


In [45]:
#[*range(-2,3)]

In [46]:
dst = np.zeros((h,w),np.int)

<ipython-input-46-6137fcb8b1c2>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [47]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [48]:
img

array([[2, 2, 3, 3, 9, 1, 0, 6, 1, 4, 1, 6],
       [2, 2, 4, 9, 2, 2, 0, 5, 7, 3, 3, 3],
       [8, 0, 2, 5, 4, 2, 4, 6, 5, 1, 0, 2],
       [8, 4, 2, 4, 3, 0, 7, 8, 3, 5, 1, 4],
       [7, 4, 3, 7, 0, 2, 1, 1, 4, 5, 3, 0],
       [3, 6, 8, 9, 3, 9, 8, 5, 5, 4, 8, 8],
       [4, 0, 3, 8, 1, 6, 5, 8, 1, 9, 1, 5],
       [4, 2, 1, 4, 7, 0, 8, 1, 6, 7, 8, 1],
       [1, 2, 9, 0, 0, 4, 9, 6, 7, 6, 3, 8],
       [4, 0, 4, 0, 3, 2, 5, 4, 6, 8, 2, 5],
       [4, 7, 7, 1, 9, 7, 2, 9, 2, 9, 8, 3],
       [5, 3, 5, 1, 1, 9, 8, 1, 8, 5, 8, 5]])

In [49]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  22, -16,   3, -11,   1,  14,  -3,   5,   0],
       [  0, -16,  -3,   1,   4,  -2,   1,   2,   3,  -9,  -7,   0],
       [  0,   2,  -5,  -1,   4, -14,  15,  15, -10,  10,  -8,   0],
       [  0,  -4,  -9,  12, -15,  -2, -14, -14,   2,   4,  -2,   0],
       [  0,   9,  11,  10,  -7,  17,  12,  -2,   6, -11,  16,   0],
       [  0, -15,  -5,  15, -20,   9, -10,  20, -24,  23, -26,   0],
       [  0,   1, -14,   0,  23, -25,  17, -24,   8,  -1,  20,   0],
       [  0,  -4,  29, -13, -14,   5,  13,   3,   4,  -1, -12,   0],
       [  0, -17,   0,  -8,   1, -11,   3, -10,   3,   9, -16,   0],
       [  0,  14,  11, -13,  24,   6, -21,  27, -24,  13,  10,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [50]:
img = cv2.imread('lena.png', 0)

In [51]:
h,w=img.shape

In [52]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [53]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [54]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()